sr_scara_hx:
  sr_scara_hx_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3

    gains:
      joint1:  {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
      joint2:  {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
      joint3:  {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}

